bootstrap/cache/services.php

storage/app/*
storage/framework/cache/*
storage/framework/sessions/*
storage/framework/views/*
storage/logs/*

**/*node_modules

**.git
.idea
**.gitignore
**.gitattributes
*.env
**.pem
